exclude:
  - AGENTS.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - node_modules
  - .gitignore
permalink: /blog/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
